[package]
name = "sync_dis_boi"
version = "0.1.0"
edition = "2021"

[dependencies]
async-recursion = "1.0.4"
async-trait = "0.1.57"
clap = { version = "*", features = ["derive", "env"] }
color-eyre = "0.6.2"
futures = "0.3.24"
reqwest = { version = "0.11.11", features = ["cookies", "json"] }
serde = "1.0.144"
serde_json = "1.0.85"
strsim = "0.10.0"
tokio = { version = "1.20.1", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
webbrowser = "0.7.1"
