[package]
name = "sync_dis_boy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.62"
async-trait = "0.1.57"
clap = { version = "3.2.19", features = ["derive"] }
futures = "0.3.24"
hex = "0.4.3"
reqwest = { version = "0.11.11", features = ["cookies", "json"] }
serde = "1.0.144"
serde_json = "1.0.85"
sha1 = "0.10.2"
tokio = { version = "1.20.1", features = ["full"] }
